### PR TITLE
Queue.subscribe!

### PR DESCRIPTION
**Pull request by baelter**
In-memory implementation of http://reference.rubybunny.info/Bunny/Queue.html#subscribe-instance_method

### CODE REVIEW

**Comment by arempe93** [comment]
Thanks for this implementation! I will look at it more closely later tonight

**Comment by baelter** [comment]
You can hold this PR until further notice, I've found some shortcomings I want to fix.

**Comment by baelter** [comment]
Ok @arempe93, happy with this now.

Added support for multiple routes with them same key. Basically `Exchange::routes` hash items are arrays of routes instead.

**Comment by arempe93** [comment]
Looks pretty good to me - only question is why call `yield_consumers` in the subscribe method? I can't think of a case where it would do anything - but maybe there is

**Comment by baelter** [comment]
Reason for that is that if there are messages in the queue they will be delivered when a consumer subscribes.

**Comment by arempe93** [comment]
Ok - that makes sense. For some reason I didn't think of the case that there could be messages entered into the queue before a subscription happens.

**Comment by baelter** [comment]
Sweet, when are u planning next release?

**Comment by arempe93** [comment]
Probably when I have time after work today. I don't think there's anything else in progress right now

**Pull request merged**
