### PR TITLE
Implement reject functionality

### PR DESCRIPTION
**Pull request by binaryberry**
This leverages the `acknowledgement_state` accessor
that was added to support ack/nack tracking. This
supports the `requeue` param.

Paired with @dwhenry

### CODE REVIEW

**Comment by arempe93** [comment]
thanks for the PR - ill try to look at this after work

**Comment by binaryberry** [comment]
Hi @arempe93, not sure if you got a chance to look at this yet? Do let us know if there is anything unclear.

**Comment by arempe93** [comment]
@binaryberry hey sorry I took a long weekend and forgot to look beforehand.

**Comment by arempe93** [comment]
Everything looks good so I'll do a 1.7.0 release sometime today

**Comment by binaryberry** [comment]
@arempe93 Thanks a lot! 😃

**Comment by binaryberry** [comment]
Hi @arempe93 ! I wanted to check in to see if you might know when you'd be releasing this? 
It'll be helpful for us knowing we're no longer relying on our own fork, but I do realise you're doing this in your own time.

**Comment by arempe93** [comment]
@binaryberry just pushed out v1.7.0 - thanks for your patience and for reminding me

**Comment by binaryberry** [comment]
@arempe93 Thank you so much for doing this! 🎉

**Pull request merged**
