### PR TITLE
Added support of Bunny::Queue#subscribe_with(callable, *)

### PR DESCRIPTION
**Pull request by tinbka**
I use this method to delegate message processing to a specific worker class.

### CODE REVIEW

**Comment by arempe93** [comment]
Look great, thanks for contributing! If you could, just fix that trailing whitespace rubocop is complaining about in `queue.rb:87`.

The build failure for JRuby looks to be related to lemurheavy/coveralls-ruby#107

**Comment by tinbka** [comment]
Fixed the whitespace thing.

Regarding jruby-d19, it fails both locally and in Travis with
```
rubocop-0.43.0 requires ruby version >= 2.0.0, which is incompatible with the
current version, ruby 1.9.3p551 (jruby 1.7.19)
```

Unfortunately, Bundler doesn't provide an easy way to track Ruby version dependencies, so either someone have to bruteforce versions of Rubocop that both support Ruby 1.9.3 and your desired config, or get rid of either Rubocop or jruby-d19 support in CI :\

**Comment by tinbka** [comment]
Fixed the whitespace thing and the versions. I've ended up fixing the dependencies to the versions listed in the last successful CI build log.

**Comment by arempe93** [comment]
Thanks! For the change and coveralls workaround :+1:

**Pull request merged**
